import pygame,sys
from pygame.locals import *
import sys, os

pygame.init()


black = (0, 0, 0)
white = (255, 255, 255)
red = (255, 0, 0)
green = (0, 200, 0)
bright_green = (0, 250, 0)



def text_objects(text, font):
	textSurface = font.render(text, True, black)
	return textSurface, textSurface.get_rect()

def mapa():

	CANTOESQUERDO = 0
	LADOESQ = 1
	GRASS = 2
	AGUAEPEDRA = 3
	CACHOEIRA = 4
	PEDRA = 5
	ESCADABAIXO = 6
	PORTAL = 7
	AGUA = 8
	LADODIR = 9
	CIMAGRAMA = 10
	BAIXOGRAMA = 11
	ESCADACIMA = 12
	CANTODIREITO = 13
	TORREE = 14
	TORRECENTRALUM = 15
	TORRECENTRAL2 = 16
	TORRECENTRAL3 = 17
	TORRECENTRAL4 = 18
	CAMINHO = 19
	CASA2 = 20
	CASA3 = 21
	CASA4 = 22
	CASA5 = 23
	FOGUEIRA1 = 24


	terrenos = [CANTOESQUERDO, LADOESQ, GRASS, AGUAEPEDRA, CACHOEIRA, PEDRA, ESCADABAIXO, PORTAL ,AGUA, LADODIR, CIMAGRAMA, BAIXOGRAMA,ESCADACIMA,CANTODIREITO, TORREE, TORRECENTRALUM, TORRECENTRAL2, TORRECENTRAL3, TORRECENTRAL4, CAMINHO, CASA2, CASA3, CASA4, CASA5, FOGUEIRA1  ]
 
	textures = {
		CANTOESQUERDO: pygame.image.load('CANTOESQUERDO.png'),
		LADOESQ: pygame.image.load('LADOESQ.png'),
		GRASS: pygame.image.load('GRASS.png'),
		AGUAEPEDRA: pygame.image.load('AGUAEPEDRA.png'),
		CACHOEIRA: pygame.image.load('CACHOEIRA.png'),
		PEDRA: pygame.image.load('PEDRA.png'),
		ESCADABAIXO: pygame.image.load('ESCADABAIXO.png'),
		PORTAL: pygame.image.load('PORTAL.png'),
		AGUA: pygame.image.load('AGUA.png'),
		LADODIR: pygame.image.load('LADODIR.png'),
		CIMAGRAMA: pygame.image.load('CIMAGRAMA.png'),
		BAIXOGRAMA: pygame.image.load('BAIXOGRAMA.png'),
		ESCADACIMA: pygame.image.load('ESCADACIMA.png'),
		CANTODIREITO: pygame.image.load('CANTODIREITO.png'),
		TORREE: pygame.image.load('TORREE.png'),
		TORRECENTRALUM: pygame.image.load('TORRECENTRALUM.png'),
		TORRECENTRAL2: pygame.image.load('TORRECENTRAL2.png'),
		TORRECENTRAL3: pygame.image.load('TORRECENTRAL3.png'),
		TORRECENTRAL4: pygame.image.load('TORRECENTRAL4.png'),
		CAMINHO: pygame.image.load('CAMINHO.png'),
		CASA2: pygame.image.load('CASA2.png'),
		CASA3: pygame.image.load('CASA3.png'),
		CASA4: pygame.image.load('CASA4.png'),
		CASA5: pygame.image.load('CASA5.png'),
		FOGUEIRA1: pygame.image.load('FOGUEIRA1.png')






	}

	TILESIZE = 40
	MAPWIDTH = 40
	MAPHEIGHT = 20

	tilemap = [
	[CANTOESQUERDO, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ,GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ ,TORRECENTRALUM, TORRECENTRAL2, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, TORRECENTRAL3, TORRECENTRAL4,CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO,CAMINHO, CAMINHO, CAMINHO, CAMINHO, CAMINHO],
	[LADOESQ, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, CANTOESQUERDO, CIMAGRAMA, CIMAGRAMA,CIMAGRAMA, CIMAGRAMA, CIMAGRAMA, CIMAGRAMA, CIMAGRAMA,CIMAGRAMA, CIMAGRAMA, CIMAGRAMA, CANTODIREITO, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ,GRASS, LADOESQ, GRASS, GRASS,GRASS, GRASS, GRASS, CASA3, CASA2, GRASS, GRASS, GRASS, LADODIR, GRASS,GRASS, GRASS,GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, LADOESQ, GRASS, GRASS,GRASS, GRASS, BAIXOGRAMA,CASA4, CASA5, FOGUEIRA1, ESCADACIMA, GRASS, LADODIR, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, LADOESQ, GRASS, AGUAEPEDRA,GRASS, LADODIR, PEDRA, PEDRA,PEDRA, PORTAL, ESCADABAIXO, PEDRA, PEDRA, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, LADOESQ, GRASS, AGUA,GRASS, LADODIR, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, LADOESQ, GRASS, AGUA,GRASS,LADODIR, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[LADOESQ, GRASS, PEDRA, PEDRA, CACHOEIRA,PEDRA, PEDRA, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS,GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS],
	[AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA, AGUAEPEDRA,AGUAEPEDRA, AGUAEPEDRA],
	[AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],
	[AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA,AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA, AGUA],

	]

	DISPLAYSURF = pygame.display.set_mode((MAPWIDTH*TILESIZE, MAPHEIGHT*TILESIZE))
	pygame.display.set_caption('Tower Defense')


	for event in pygame.event.get():
		if event.type == QUIT:
			pygame.quit()
			sys.exit()

	for row in range(MAPHEIGHT):

		for column in range(MAPWIDTH):
			DISPLAYSURF.blit(textures[tilemap[row][column]], (column*TILESIZE,row*TILESIZE))
	return DISPLAYSURF
mapa()